### ISSUE TITLE
Support for AS6706T is confirmed

### ISSUE THREAD

**Issue by LPJon** [mafredri/asustor-platform-driver#12]
Just letting you know support for the AS6706T platform is confirmed. Your assumptions about the GPIO pins for disks 5 and 6 are also correct.  (As suggested in your asustor.c file.)

**Comment by DanielGibson** [comment]
Thanks for confirming my assumptions about the SATA 5 and 6 LEDs!
I made the corresponding changes in #16, can you test them? :)

**Comment by LPJon** [comment]
@DanielGibson I can confirm that your code lines up with what I have. I made some tweeks to use the red LED's for activity and green for power. 

LED CONFIG SETTINGS:
```
        {
                .name            = "sata5:green:disk", // 17
                .default_state   = LEDS_GPIO_DEFSTATE_ON,
                //.default_trigger = "disk-activity",
        },
        { .name         = "sata5:red:disk",
                .default_state = LEDS_GPIO_DEFSTATE_ON, // 18
                .default_trigger = "disk-activity"},
        {
                .name            = "sata6:green:disk", // 19
                .default_state   = LEDS_GPIO_DEFSTATE_ON,
                //.default_trigger = "disk-activity",
        },
        { .name         = "sata6:red:disk",
                .default_state = LEDS_GPIO_DEFSTATE_ON, // 20
                .default_trigger = "disk-activity"},
};
```
GPIO DRIVER:
```
                GPIO_LOOKUP_IDX(GPIO_IT87, 61, NULL, 17, GPIO_ACTIVE_HIGH),     // sata5:green:disk
                GPIO_LOOKUP_IDX(GPIO_IT87, 62, NULL, 18, GPIO_ACTIVE_LOW),      // sata5:red:disk
                GPIO_LOOKUP_IDX(GPIO_IT87, 58, NULL, 19, GPIO_ACTIVE_HIGH),     // sata6:green:disk
                GPIO_LOOKUP_IDX(GPIO_IT87, 60, NULL, 20, GPIO_ACTIVE_LOW),      // sata6:red:disk
```

**Comment by DanielGibson** [comment]
Did you also make those changes for SATA1-4 or is my code for SATA5/6 not consistent with the existing behavior of 1-4?

**Comment by LPJon** [comment]
Yes I also made those changes for 1-4. Your code is consistant.

**Comment by mafredri** [comment]
Unless I missed something, I think we made all the necessary changes to the code thanks to Daniel. Thanks for your report @LPJon.

PS. You can change the behavior without modifying the module:

```
for i in $(seq 1 6); do
	echo off > /sys/class/leds/sata${i}:green:disk/trigger
	echo disk-activity > /sys/class/leds/sata${i}:red:disk/trigger
done
```

You could add that to a systemd script that starts at boot or if your system has it, `/etc/rc.local`. (Or initramfs if you want it to change even earlier.)

**Comment by DanielGibson** [comment]
Hi @LPJon, could you post the output of
`$ sudo lspci -nn`
and
`$ sudo lspci -tv -nn`

I want to make sure my Flashstor detection (#27) doesn't break support for AS6706T :)

Thanks in advance!
