### ISSUE TITLE
PWM always inverted as5402t

### ISSUE THREAD

**Issue by vincentDcmps** [mafredri/asustor-platform-driver#14]
Hi I have install module asustor_gpio_it87 and asustor_it87 only because my archlinux don't seem to have gpio-inch availlable

sensors are correctly detected 
```
[    0.775619] asustor_gpio_it87: loading out-of-tree module taints kernel.
[    0.775626] asustor_gpio_it87: module verification failed: signature and/or required key missing - tainting kernel
[    0.775910] asustor_gpio_it87: Found Chip IT8625 rev d. 64 GPIO lines starting at 0a00h
[    0.781784] asustor_it87: Found IT8625E chip at 0xa30, revision 13
[    0.781862] asustor_it87: Beeping is supported
```

but pwm command are always inverted so can't use pwmconfig to configure fan control
does someone have a solution on that?

**Comment by mafredri** [comment]
@vincentDcmps that's interesting, this is the first ASUSTOR NAS I know of that uses active high PWM polarity by default, if that's the case.

However, before we assume that, is there any chance that you are/have loaded the regular `it87` driver, and used the `fix_pwm_polarity` module option?

PS. I don't know if the `gpio-ich` driver will be useful to you, but if you want it, here's what I use on my AS-6204T (`make dkms`): [gpio-ich.zip](https://github.com/mafredri/asustor-platform-driver/files/14393579/gpio-ich.zip)

**Comment by vincentDcmps** [comment]
correct I have test regular it87 with fix_pwm_polarity before but I remove this module before to install your own

**Comment by mafredri** [comment]
Could you try completely powering off the NAS (pull the power plug, even), then power it on again? I'm mostly curious if the `fix_pwm_polarity` you tried before is still messing it up, and perhaps the firmware doesn't restore it on boot. (Also if you can access the motherboard battery, you could try removing it for 30 seconds while power is unplugged, then putting it back and powering up).

If you still are able to boot into ASUSTOR ADM, I would also be interested to know if the fans work correctly there, and once confirmed, try one more time booting into Linux and seeing if it works correctly with the `asustor_it87` module.

These tests are mainly to confirm that we don't make the wrong assumption about default configuration for the AS54.

**Comment by DanielGibson** [comment]
The AS5402T is the one I have, it doesn't need/use gpio-ich, as far as I can tell.

What do you mean exactly with PWM controls are inverted?
On my system, `pwm1` in `/sys/devices/platform/asustor_it87.*/hwmon/hwmon*/` controls the fan, and setting it to `28` sets about 800RPM, while `50` sets about 1200RPM, so a higher value sets higher RPM, which should be the expected behavior?

`pwm3` however, which controls the LED brightness, indeed seems to be inverted, I set it to `200` to have a low brightness.

**Comment by vincentDcmps** [comment]
From my side I have max rpm xhen pwm is 0 and min rpm when pwm is 255

**Comment by vincentDcmps** [comment]
About gpio-inch I think I don t need it
Issue meet during asustor.c compilation is due to 
Replacement of gpiochip_find() with gpio_device_find() un last linux kernel

**Comment by vincentDcmps** [comment]
just text this morning after a shutdown and pull power plug,  thanks a lot for your help!!!

**Comment by vincentDcmps** [comment]
I have try to modify asustor.c to switch to gpio_device_find 
first time I modify C code :) could you tell me if seems good?
https://github.com/vincentDcmps/asustor-platform-driver

**Comment by DanielGibson** [comment]
> just text this morning after a shutdown and pull power plug, thanks a lot for your help!!!

does this mean that `pwm1` now works as it should (higher value = higher RPM)?

(I'll look at the changed code later)

**Comment by vincentDcmps** [comment]
yes correct, I didn't know that some kernel module option can persist after a reboot...

**Comment by DanielGibson** [comment]
> first time I modify C code :) could you tell me if seems good?
> https://github.com/vincentDcmps/asustor-platform-driver

Sorry, this does not look too good, mostly because the real `struct gpio_device` looks very different, so this wouldn't work (wouldn't return the gpio_chip but some garbage data).

However, could you try if my change in #15 works for you? :)
I haven't tested it (don't have a new enough kernel), but I *think* it should work somehow like this

**Comment by DanielGibson** [comment]
BTW:
> yes correct, I didn't know that some kernel module option can persist after a reboot...

and this assumption is true, mostly - except in this case the kernel option seems to set some flag in the hardware (the it87 chip) that apparently persists across reboots, but is reset when disconnecting the power plug
