### ISSUE TITLE
AS5402T memory leak

### ISSUE THREAD

**Issue by vincentDcmps** [mafredri/asustor-platform-driver#19]
Hi I use archlinux on my AS5402T and I have a memory leak memory use is always growing but I don't see any application who use it.
somebody have already meet this type of issue on this hardware?

![Capture d’écran du 2024-03-31 11-39-49](https://github.com/mafredri/asustor-platform-driver/assets/29679418/716cfcb8-3c30-4aeb-ba6a-c7024b927a0a)

**Comment by mafredri** [comment]
Hi, unless you’ve found a memory leak caused by this kernel module, this is not the right place to ask for support. I would suggest asking in some Arch Linux community/forum.
