### ISSUE TITLE
Asustor AS6604T

### ISSUE THREAD

**Issue by DOcGui** [mafredri/asustor-platform-driver#3]
Hello,
If you have some time to look for my Asustor AS6604T
But I think we will have the same problem with IT8625E
Ask me if you need more information

```
# sudo dmidecode -s system-manufacturer
Insyde

# sudo dmidecode -s system-product-name
GeminiLake

# sudo dmidecode -s bios-vendor
INSYDE Corp.

# sudo dmidecode -s bios-version
V1.1C

# sudo dmidecode -s bios-release-date
03/20/2020

# sudo dmidecode -s bios-revision
1.25
```

[gpioinfo.txt](https://github.com/mafredri/asustor-platform-driver/files/10579295/gpioinfo.txt)
[dmesg.txt](https://github.com/mafredri/asustor-platform-driver/files/10579296/dmesg.txt)

**Comment by DOcGui** [comment]
Could the work of this ones help?
https://github.com/a1wong/it87

**Comment by mafredri** [comment]
I’ll take a look once I have some time. In the meantime, if you want to give the it87 branch in this repo a spin, feel free: https://github.com/mafredri/asustor-platform-driver/tree/it87

**Comment by DanielGibson** [comment]
Hi, I've got the Asustor AS6602T (Lockerstore 2), and get the exact same output from dmidecode.

I'm running latest Debian stable (Bookworm 12.1) on it, with kernel 6.1.0-12-amd64 (standard Debian kernel).

The astor_it87 module from the branch linked above works, `sensors` outputs values that seem plausible, and I can control the fanspeed and LED brightness through `/sys/devices/platform/asustor_it87.656/hwmon/hwmon3/pwm1` and `pwm3` in the same directory.
(Ok, is it really plausible that the fanspeed is 1222 by default and goes up to 5000RPM at pwm 255? It *does* sound like a jet engine at max speed, though..)

Anyway, the `asustor` module itself doesn't work: `modprobe: ERROR: could not insert 'asustor': No such device`

[gpioinfo.txt](https://github.com/mafredri/asustor-platform-driver/files/12775829/gpioinfo.txt)
[dmesg.txt](https://github.com/mafredri/asustor-platform-driver/files/12775838/dmesg.txt)

If you can give me some hints on how to test those GPIO pins, I might try to create a patch myself - would love to get rid of the blinking green LED after boot (with the original software it turns to steadily lit once it's done booting)

**Comment by DanielGibson** [comment]
Also possibly relevant, the gpio-it87 driver doesn't load, dmesg says:
`gpio_it87: Unknown Chip found, Chip 8625 Revision 8`

(it's also not included in Debian's kernel package, so I built [the latest code for it](https://github.com/torvalds/linux/blob/master/drivers/gpio/gpio-it87.c) myself, with the Makefile from [here](https://github.com/Moxa-Linux/moxa-it87-gpio-driver/blob/master/Makefile))

`gpio_ich` (built similarly) *does* load, but that doesn't give me any new GPIO chips in gpiodetect or gpioinfo

**Comment by DanielGibson** [comment]
I had a quick look at asustors kernel source (from https://sourceforge.net/projects/asgpl/files/ADM4.1.0/4.1.0.RLQ1_and_above/x64g3_adm41_kernel_5_13_x/) and they have patched gpio-it87.c (and lots of other files).
I hope to find some time to port their changes to this repo (incl. adding asustor_gpio_it87.c) soonish, to get asustor.ko to work on my AS6602T (and probably other machines as well)

**Comment by DanielGibson** [comment]
I extracted the bzImage from the ADM, and extracted that to vmlinux, and checked if the `to_load_it87()` and/or `asustor_model_check()` functions exist in it (ok, I just ran strings on it and grepped for those identifiers).

Anyway, they do.

I also built the kernel source from https://sourceforge.net/projects/asgpl/files/ADM4.1.0/4.1.0.RLQ1_and_above/x64g3_adm41_kernel_5_13_x/ myself (with the kernel config provided there), and the resulting vmlinux does **not** contain `to_load_it87` or `asustor_model_check`, so I'm quite certain that the kernel source they're providing is incomplete.

I filed a support request with asustor, requesting the full source and describing my findings, we'll see how that goes..

**Comment by DanielGibson** [comment]
Hi @DOcGui I patched the it87 branch to (hopefully) support the AS660xT as well, but I don't have such a device (anymore).
Can you test my branch? https://github.com/DanielGibson/asustor-platform-driver/tree/it87-jasperlake

**Comment by mafredri** [comment]
All of @DanielGibson's changes have been merged in, so feel free to try the `main` branch  @DOcGui and let us know if it works.
