### ISSUE TITLE
Asustor AS6706T gen 2 additional leds and lcd

### ISSUE THREAD

**Issue by hlugt** [mafredri/asustor-platform-driver#9]
Hi, I have implemented your module and I can now manage my fanspeed: thanks!

For the AS6706T 2 of the 6 sata leds are missing. Trying to figure out how to find out the gpio's for the 5th and 6th bay leds, but it is not clear to me how you do it. Can you explain or maybe if you know them, give them, so I can try to add them to the asusstor.c ? 
Also it is not clear to me whether the lcd should function? It is stuck to "system starting please wait..." on my box? 

Tia

**Comment by mafredri** [comment]
You could try the pins mentioned here: https://github.com/mafredri/asustor-platform-driver/blob/534aa162bb2639f525864cfe9c0c2caf9c386f32/asustor.c#L149

You’ll also need to create entries for them here: https://github.com/mafredri/asustor-platform-driver/blob/534aa162bb2639f525864cfe9c0c2caf9c386f32/asustor.c#L29

for the LCD, please use lcm/openlcmd from here: https://github.com/mafredri/lcm/tree/main#installation

**Comment by hlugt** [comment]
Ah great, will check this out. Thx!
